# Generated by Django 4.0 on 2021-12-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20211230_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
